// examples/vue3-lib/src/components/HelloWorld.vue
<template>
  <div class="hello-world">
    <h2>{{ greeting }}</h2>
    <p class="message">{{ message }}</p>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  name: {
    type: String,
    default: 'World',
  },
  message: {
    type: String,
    default: 'This component is from ikaros vue3 library example.',
  },
})

const greeting = computed(() => `Hello, ${props.name}!`)
</script>

<style scoped>
.hello-world {
  padding: 16px 24px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  text-align: center;
  font-family: sans-serif;
}

.hello-world h2 {
  margin: 0 0 8px;
  color: #42b883;
}

.hello-world .message {
  margin: 0;
  color: #666;
  font-size: 14px;
}
</style>

// examples/react-lib/src/components/HelloWorld.jsx
import React from 'react'

const styles = {
  container: {
    padding: '16px 24px',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    textAlign: 'center',
    fontFamily: 'sans-serif',
  },
  title: {
    margin: '0 0 8px',
    color: '#61dafb',
  },
  message: {
    margin: 0,
    color: '#666',
    fontSize: '14px',
  },
}

export function HelloWorld({
  name = 'World',
  message = 'This component is from ikaros react library example.',
}) {
  return (
    <div style={styles.container}>
      <h2 style={styles.title}>Hello, {name}!</h2>
      <p style={styles.message}>{message}</p>
    </div>
  )
}
